# Generated by Django 5.0.6 on 2025-02-19 07:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Book_Appointment", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="slots",
            field=models.CharField(max_length=100),
        ),
    ]
